#!/usr/bin/env bash
# Regenerates DIFFS.md from the drafts in this directory.
#
# The diffs are the point of the experiment: what a linter's findings actually
# change about a document, measured rather than asserted. Kept as a script so the
# file can be refreshed after a rerun instead of hand-assembled.
set -euo pipefail
cd "$(dirname "$0")"

# Absolute path: the subshell changes directory to find the project venv, so a
# relative argument would resolve against the wrong directory and lint nothing.
HERE="$PWD"
lint() { (cd ../packages/slopvac-lint && uv run slopvac "$HERE/$1" 2>&1) || true; }

{
  printf '# Clean-room README experiment: diffs\n\n'
  printf 'Generated by `make-diffs.sh`. Do not hand-edit.\n\n'

  printf '## What this measures\n\n'
  cat <<'PROSE'
An agent wrote a README for `slopvac-lint` from the package source alone, under
`claude -p --bare`: no hooks, no CLAUDE.md discovery, no plugin sync. It was
forbidden from reading the existing README, the rule YAML, the profile tables,
the generated rules reference, and any writing-style guidance. It was told to
write in its default voice and to avoid nothing in particular.

The linter then graded it. The findings went back to the same agent, which had
still never seen a rule definition, only the finding messages a real user gets.
It rewrote from those.

`README.contaminated.md` is an earlier run of the same task WITHOUT `--bare`. It
is here as the control: that agent had absorbed the ruleset from ambient context
and wrote to it pre-emptively, which is the effect `--bare` removes.

v3 and v4 continue the same chain and test the other half of the ruleset. 67 of
the rules are `kind: judgement`: they state a question a reviewer answers and no
pattern decides, so nothing above measured them at all. Four read-only judges
took v2 (`v3/subject.md`, byte-identical to `README.v2.md`), one scope each --
sentence, paragraph, document, prose -- and produced 62 findings between them.
The scopes were split so that no reviewer held all 67 questions at once; the
document-scope pass found 11 whole-text shape problems a single reviewer juggling
everything would likely have skipped.

A separate agent then rewrote from those findings, and saw the judges' findings
only -- never their reasoning, and never the mechanical ruleset. That is v3, and
it scored WORSE than what it replaced: 75.8 against 87.3. It fixed judgement
defects and bought pattern defects, because nobody had told it there were
patterns. v4 is the missing half: the same document, edited a second time against
the mechanical findings alone, with the judgement fixes declared off-limits.

v4 is where the ruleset itself was caught contradicting itself. Obeying
`ste-sentences.complex-text-not-in-vertical-list` 15 times produced 15 list
stems, and `emphasis-paragraph-metric` reported 7 of them as one-fragment
emphasis paragraphs. Two shipped rules, no move that satisfied both. The
exclusion that fixes it exists because this experiment ran.
PROSE
  printf '\n\n## Documents\n\n'
  printf '| file | lines | words | em dashes | what it is |\n'
  printf '|---|---|---|---|---|\n'
  for f in README.v1.md README.v2.md v3/README.v3.md v3/README.v4.md \
           README.contaminated.md README.human.md; do
    [ -f "$f" ] || continue
    case "$f" in
      README.v1.md)           what='clean-room first draft' ;;
      README.v2.md)           what='rewritten from the findings' ;;
      v3/README.v3.md)        what='v2 rewritten from 62 JUDGEMENT findings' ;;
      v3/README.v4.md)        what='v3 edited again from the mechanical findings' ;;
      README.contaminated.md) what='control: no --bare, ruleset pre-internalised' ;;
      README.human.md)        what='hand-written; a SNAPSHOT of the committed README, which has moved on since' ;;
    esac
    printf '| `%s` | %s | %s | %s | %s |\n' "$f" \
      "$(grep -c '' "$f" | tr -d ' ')" "$(wc -w < "$f" | tr -d ' ')" \
      "$(grep -o '—' "$f" | wc -l | tr -d ' ')" "$what"
  done

  printf '\n## Scores\n\n```\n'
  for f in README.v1.md README.v2.md v3/README.v3.md v3/README.v4.md \
           README.contaminated.md README.human.md; do
    [ -f "$f" ] || continue
    printf '%s\n' "$f"
    lint "$f" | grep -E '^(FAIL|PASS|  x |  ! )' || true
    printf '\n'
  done
  printf '```\n'

  printf '\n## v1 to v2: the rewrite\n\n'
  printf 'What the findings changed.\n\n```diff\n'
  diff -u README.v1.md README.v2.md || true
  printf '```\n'

  printf '\n## v2 to v3: what a judgement review changes\n\n'
  printf 'The 62 findings here name no pattern. Every one is a question a\n'
  printf 'reviewer answered, from four scopes read separately.\n\n```diff\n'
  diff -u README.v2.md v3/README.v3.md || true
  printf '```\n'

  printf '\n## v3 to v4: the mechanical half, applied second\n\n'
  printf 'The judgement fixes were declared off-limits, so this diff is the cost\n'
  printf 'of the ruleset alone.\n\n```diff\n'
  diff -u v3/README.v3.md v3/README.v4.md || true
  printf '```\n'

  if [ -f README.human.md ]; then
    printf '\n## v4 against the hand-written README\n\n'
    printf 'Two documents describing the same package, one written by an agent from\n'
    printf 'source and reviewed twice, one written by hand.\n\n```diff\n'
    diff -u README.human.md v3/README.v4.md || true
    printf '```\n'
  fi

  printf '\n## v1 against the contaminated control\n\n'
  printf 'The same task, same model, with and without ambient rule knowledge.\n\n```diff\n'
  diff -u README.contaminated.md README.v1.md || true
  printf '```\n'
} > DIFFS.md

printf 'wrote DIFFS.md (%s lines)\n' "$(wc -l < DIFFS.md | tr -d ' ')"
