from __future__ import annotations

from pathlib import Path
from types import SimpleNamespace

from slopvac.analyze import BlockKind, Document, parse
from slopvac.projection import ProjectionMap, classify_origin, classify_region, project


def test_projection_maps_unicode_entities_crlf_markup_and_code() -> None:
    raw = (
        "Café &eacute; 😊\r\n"
        "Use `inline code` and **bold**.\r\n"
        "> quoted text\r\n"
        "```python\r\n"
        "not prose\r\n"
        "```\r\n"
    )
    text, mapping = project(raw)

    assert "Café é 😊" in text
    assert "inline code" not in text
    assert "bold" in text
    assert "not prose" not in text
    assert any(segment.raw_start == segment.raw_end for segment in mapping.segments)
    for segment in mapping.segments:
        if segment.raw_start < segment.raw_end:
            projected = text[segment.proj_start : segment.proj_end]
            assert mapping.slice_raw(segment.proj_start, segment.proj_end).decode() == projected


def test_projection_line_join_is_a_zero_width_raw_segment() -> None:
    text, mapping = project("first line\r\nsecond line")
    join = text.index("second") - 1
    segment = mapping.segments[join]

    assert segment.raw_start == segment.raw_end
    assert mapping.to_raw(join) < mapping.to_raw(join + 1)
    assert mapping.slice_raw(0, 5) == b"first"
    assert mapping.slice_raw(text.index("second"), text.index("second") + 6) == b"second"


def test_origin_classification_table() -> None:
    assert classify_origin("docs/rules.md", "<!-- generated by slopvac -->\n") == "generated"
    assert classify_origin("CHANGELOG.md") == "generated"
    assert classify_origin(".agents/generated.md") == "vendored"
    assert classify_origin("fixtures/example.md") == "template"
    assert classify_origin("README.md") == "authored"


def test_region_classification_and_examples_heading() -> None:
    assert classify_region(SimpleNamespace(kind=BlockKind.QUOTE)) == "quoted"
    assert classify_region(SimpleNamespace(kind=BlockKind.CODE)) == "code"
    assert (
        classify_region(
            SimpleNamespace(kind=BlockKind.LIST_ITEM, text="bad", examples=["bad"])
        )
        == "example"
    )
    assert classify_region(SimpleNamespace(kind=BlockKind.PARAGRAPH)) == "prose"

    document = parse("guide.md", "## Examples\n\n- bad example\n\nPlain paragraph.\n")
    items = [block for block in document.blocks if block.kind is BlockKind.LIST_ITEM]
    paragraphs = [block for block in document.blocks if block.kind is BlockKind.PARAGRAPH]
    assert items and items[0].region_class == "example"
    assert paragraphs and paragraphs[-1].region_class == "example"


def test_block_id_is_stable_and_source_sensitive() -> None:
    raw = "A paragraph.\n"
    first = parse("README.md", raw).blocks[0]
    second = parse("README.md", raw).blocks[0]
    changed = parse("README.md", "A paragraph!\n").blocks[0]

    assert first.id == second.id
    assert first.id != changed.id
    assert first.source_sha256 == second.source_sha256
    assert first.doc_range == first.range
    assert first.projection is not None

def test_document_projection_is_a_projection_map() -> None:
    document = parse("README.md", "```\nignored\n```\n\nVisible paragraph.\n")

    assert isinstance(document, Document)
    assert isinstance(document.projection, ProjectionMap)


def test_later_blocks_use_document_projection_offsets() -> None:
    raw = "```\nignored\n```\n\nLater paragraph.\n\n| A | B |\n| - | - |\n| cell | value |\n"
    document = parse("fixture.md", raw)
    paragraph = next(block for block in document.blocks if block.kind is BlockKind.PARAGRAPH)
    table = next(block for block in document.blocks if block.kind is BlockKind.TABLE)
    projected, _ = project(raw)

    assert paragraph.doc_range == (projected.index("Later paragraph."), projected.index("Later paragraph.") + len(paragraph.text))
    assert table.doc_range[0] == projected.index("A | B")
    assert table.doc_range[0] > paragraph.doc_range[1]


def test_nonzero_offset_unit_projection_round_trips_raw_bytes() -> None:
    raw = "Intro paragraph.\n\n```\nignored\n```\n\nVisible paragraph.\n"
    block = next(block for block in parse("fixture.md", raw).blocks if block.text == "Visible paragraph.")

    assert block.doc_range[0] > 0
    assert block.projection is not None
    assert block.projection.slice_raw(0, len(block.text)) == block.text.encode()


def test_readme_units_do_not_start_mid_word() -> None:
    root = Path(__file__).parents[3]
    raw = (root / "README.md").read_text(encoding="utf-8")
    projected, _ = project(raw)
    document = parse("README.md", raw)

    for block in document.blocks:
        if not block.text or block.doc_range[0] == 0:
            continue
        start = block.doc_range[0]
        assert not (projected[start - 1].isalnum() and projected[start].isalnum())


def test_segment_ids_survive_unrelated_insertions() -> None:
    raw = (
        "---\n"
        "title: Fixture\n"
        "---\n\n"
        "First paragraph.\n\n"
        "| A | B |\n"
        "| - | - |\n"
        "| C | D |\n"
        "| E | F |\n\n"
        "- List item.\n\n"
        "```text\n"
        "ignored code.\n"
        "```\n\n"
        "Привет мир.\n"
    )
    inserted = raw.replace("First paragraph.", "Inserted paragraph.\n\nFirst paragraph.")

    def identities(document):
        blocks: dict[tuple[str, str], int] = {}
        sentences: dict[str, int] = {}
        values = {}
        for block in document.blocks:
            block_key = (block.kind.value, block.text)
            block_index = blocks.get(block_key, 0)
            blocks[block_key] = block_index + 1
            values[("block", block_key, block_index)] = block.id
            for sentence in block.sentences:
                sentence_index = sentences.get(sentence.text, 0)
                sentences[sentence.text] = sentence_index + 1
                values[("sentence", sentence.text, sentence_index, block.kind.value)] = sentence.id
        return values

    before = parse("fixture.md", raw)
    after = parse("fixture.md", inserted)
    before_ids = identities(before)
    after_ids = identities(after)

    for key, value in before_ids.items():
        assert after_ids[key] == value
    inserted_id = next(sentence.id for sentence in after.sentences if sentence.text == "Inserted paragraph.")
    assert inserted_id not in before_ids.values()


def test_unbordered_table_cells_keep_source_spans() -> None:
    raw = "a | b\n--- | ---\nc | d\ne | f\n"
    table = next(block for block in parse("table.md", raw).blocks if block.kind is BlockKind.TABLE)

    assert [sentence.text for sentence in table.sentences] == ["a", "b", "c", "d", "e", "f"]
    for sentence in table.sentences:
        assert sentence.source_spans
        assert "".join(raw[start:end] for start, end in sentence.source_spans) == sentence.text


def test_html_spans_ignore_attribute_values() -> None:
    raw = '<p title="Hello">Hello world.</p>'
    sentence = parse("fixture.html", raw).sentences[0]

    assert sentence.text == "Hello world."
    assert sentence.source_spans
    assert sentence.source_spans[0][0] == raw.index("Hello", raw.index(">"))
    assert sentence.source_spans[0][0] != raw.index("Hello")
    assert "".join(raw[start:end] for start, end in sentence.source_spans) == sentence.text


def test_html_spans_follow_repeated_text_nodes() -> None:
    raw = '<p title="Hello">Hello <b>Hello</b> world.</p>'
    sentence = parse("fixture.html", raw).sentences[0]

    assert len(sentence.source_spans) == 3
    assert sentence.source_spans[0][0] == raw.index("Hello", raw.index(">"))
    assert sentence.source_spans[1][0] == raw.index("Hello", sentence.source_spans[0][1])
    assert sentence.source_spans[0][0] != raw.index("Hello")
