from __future__ import annotations

from types import SimpleNamespace

from slopvac.analyze import BlockKind, Unit, parse
from slopvac.projection import classify_origin, classify_region, project


def test_projection_maps_unicode_entities_crlf_markup_and_code() -> None:
    raw = (
        "Café &eacute; 😊\r\n"
        "Use `inline code` and **bold**.\r\n"
        "> quoted text\r\n"
        "```python\r\n"
        "not prose\r\n"
        "```\r\n"
    )
    text, mapping = project(raw)

    assert "Café é 😊" in text
    assert "inline code" not in text
    assert "bold" in text
    assert "not prose" not in text
    assert any(segment.raw_start == segment.raw_end for segment in mapping.segments)
    for segment in mapping.segments:
        if segment.raw_start < segment.raw_end:
            projected = text[segment.proj_start : segment.proj_end]
            assert mapping.slice_raw(segment.proj_start, segment.proj_end).decode() == projected


def test_projection_line_join_is_a_zero_width_raw_segment() -> None:
    text, mapping = project("first line\r\nsecond line")
    join = text.index("second") - 1
    segment = mapping.segments[join]

    assert segment.raw_start == segment.raw_end
    assert mapping.to_raw(join) < mapping.to_raw(join + 1)
    assert mapping.slice_raw(0, 5) == b"first"
    assert mapping.slice_raw(text.index("second"), text.index("second") + 6) == b"second"


def test_origin_classification_table() -> None:
    assert classify_origin("docs/rules.md", "<!-- generated by slopvac -->\n") == "generated"
    assert classify_origin("CHANGELOG.md") == "generated"
    assert classify_origin(".agents/generated.md") == "vendored"
    assert classify_origin("fixtures/example.md") == "template"
    assert classify_origin("README.md") == "authored"


def test_region_classification_and_examples_heading() -> None:
    assert classify_region(SimpleNamespace(kind=BlockKind.QUOTE)) == "quoted"
    assert classify_region(SimpleNamespace(kind=BlockKind.CODE)) == "code"
    assert (
        classify_region(
            SimpleNamespace(kind=BlockKind.LIST_ITEM, text="bad", examples=["bad"])
        )
        == "example"
    )
    assert classify_region(SimpleNamespace(kind=BlockKind.PARAGRAPH)) == "prose"

    document = parse("guide.md", "## Examples\n\n- bad example\n\nPlain paragraph.\n")
    items = [block for block in document.blocks if block.kind is BlockKind.LIST_ITEM]
    paragraphs = [block for block in document.blocks if block.kind is BlockKind.PARAGRAPH]
    assert items and items[0].region_class == "example"
    assert paragraphs and paragraphs[-1].region_class == "example"


def test_unit_id_is_stable_and_source_sensitive() -> None:
    raw = "A paragraph.\n"
    first = parse("README.md", raw).blocks[0]
    second = parse("README.md", raw).blocks[0]
    changed = parse("README.md", "A paragraph!\n").blocks[0]

    def make(block) -> Unit:
        return Unit(
            kind="SPAN_CANDIDATE",
            rule_id="example-rule",
            path="README.md",
            text=block.text,
            range=block.range,
            doc_range=block.doc_range,
            projection=block.projection,
            origin=block.origin,
            region_class=block.region_class,
            source_sha256=block.source_sha256,
        )

    assert make(first).unit_id == make(second).unit_id
    assert make(first).unit_id != make(changed).unit_id
    assert first.source_sha256 == second.source_sha256
    assert first.doc_range == first.range
    assert first.projection is not None
